name: Deploy PR Preview
on: [pull_request]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-ruby@v1
        with:
          ruby-version: '2.6'
      - name: Install dependencies
        run: bundle install
      - name: Build site
        run: JEKYLL_ENV=production bundle exec jekyll build --verbose
      - name: Deploy preview
        uses: mhausenblas/mkdocs-deploy-gh-pages@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CUSTOM_DOMAIN: ${{ github.repository_owner }}.github.io
          SITE_DIR: _site
          BRANCH_NAME: pr-${{ github.event.number }}
